[package]
name = "crunch-asset-hub-paseo"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-core = { path = "../../core" }
crunch-config = { path = "../../config" }
crunch-error = { path = "../../error" }
crunch-pools = { path = "../../pools" }
crunch-report = { path = "../../report" }
crunch-stats = { path = "../../stats" }
crunch-people-paseo = { path = "../people-paseo" }

async-recursion = { workspace = true }
log = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
